### ISSUE TITLE
Handle form submisions

### ISSUE THREAD

**Issue by rubenmoya** [acidtango/acid_web#11]
### Context
In the footer of the website we have a contact form, right  now it does nothing when submitted, we need to handle the form submission somehow.

### Possible solutions

- [Netlify forms](https://www.netlify.com/docs/form-handling/)
- [Send emails through Nuxt.js](https://blog.lichter.io/posts/sending-emails-through-nuxtjs/) (we'd need another host solution)
- Custom backend
- ?

**Comment by miasalazar** [comment]
We could use https://formspree.io/

**Comment by rubenmoya** [comment]
Closed by #33
